#!/usr/bin/env bash
source ./rosenv.sh
echo "Running time jump..."
rosrun time_jump time_jump.py &> time_jump.log &
echo "Running user tracker..."
rosrun kinect_based_arm_tracking tf_user_tracker.py &> user_tracker.log &
echo "Running kinect arm controller"
rosrun kinect_based_arm_tracking pose_controller.py &> pose_controller.log &
echo "Running kinect arm publisher"
rosrun kinect_based_arm_tracking pose_pub.py &> pose_pub.log &
echo "Ready! - For rosbag sim run: rosbag play <bagfile> /tf:=/tf_old"
